version: '3.1'

services:
  db:
    image: postgres:14.3
    restart: always
    container_name: financas-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: financas
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgress:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1
    restart: always
    container_name: financas-adminer
    ports:
      - 8909:8080
